### ISSUE TITLE
demo_cn 运行报错，networkx 版本2.8，python 3.8

### ISSUE THREAD

**Issue by wangxu666** [wukan1986/expr_codegen#23]
<img width="591" alt="微信图片_20240409165132" src="https://github.com/wukan1986/expr_codegen/assets/23353268/e1104180-4ef2-491e-ac5a-5673c735021b">

**Comment by wukan1986** [comment]
`ast.unparse` 函数是Python 3.9才有，是否升级3.9后再试？
